version: "3.2"

services:
  bitcoinsatellite:
    image: "samouraiwallet/dojo-bitcoinsatellite:${DOJO_BITCOIND_VERSION_TAG}"
    container_name: bitcoinsatellite
    build:
      context: ./bitcoinsatellite
    env_file:
      - ./.env
      - ./conf/docker-common.conf
      - ./conf/docker-bitcoind.conf
    restart: always
    command: "/wait-for-it.sh tor:9050 --timeout=720 --strict -- /restart.sh"
    expose:
      - "8333"
      - "28256"
      - "9501"
      - "9502"
    volumes:
      - data-bitcoind:/home/bitcoin/.bitcoin
      - data-tor:/var/lib/tor
    depends_on:
      - db
      - tor
      - blocksat2
    networks:
      dojonet:
        ipv4_address: 172.28.1.5

  node:
    depends_on:
      - bitcoinsatellite

volumes:
  data-bitcoind:
